### ISSUE TITLE
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

### ISSUE THREAD

**Issue by TudorGruian** [benoitc/gunicorn#1750]
On Ubuntu 17.10
After upgrading Pip to 9.0.3,whenever I try to run gunicorn3,it gives me this

> tudor@tudor-ThinkPad:~/Desktop/FlBot$ gunicorn3
Traceback (most recent call last):
  File "/usr/bin/gunicorn3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

I also tried reinstalling pip and even gunicorn (sudo apt download gunicorn3 and sudo dpkg -i *insert gunicorn3 package name*)

Temporarely I use it on a Pi3 via SSH

**Comment by jamadden** [comment]
Updating pip on Ubuntu is tricky because of the way they vendor things. That's almost certainly the issue, nothing to do with gunicorn. You can find several stackoverflow questions and such with https://www.google.com/search?client=safari&rls=en&q=ubuntu+pkg_resources+SourceFileLoader&ie=UTF-8&oe=UTF-8 One of those might fix it for you.

**Comment by TudorGruian** [comment]
@jamadden thanks i'll see what i can do.i will come back with a update

**Comment by benoitc** [comment]
closing the issue. no update since awhile. I didn't reproduced it as well
