### ISSUE TITLE
eventlet 0.34.1 doesnt work with gunicorn 21.2.0

### ISSUE THREAD

**Issue by Badrmoh** [benoitc/gunicorn#3120]
When installing `gunicorn[eventlet]==21.2.0` it eventually gives an error `AttributeError: module 'eventlet' has no attribute '__version__'` when running gunicorn.
`eventlet==0.34.1` has been released on 20th December and it seems to be not compatible with `gunicorn==21.2.0`

**Comment by 4383** [comment]
Fix proposed https://github.com/eventlet/eventlet/pull/859

**Comment by 4383** [comment]
Should be fixed now.

**Comment by Badrmoh** [comment]
Thanks alot

**Comment by 4383** [comment]
You are welcome
