### ISSUE TITLE
Critical Worker Timeouts With Version 20.0.3 and Up

### ISSUE THREAD

**Issue by umityayla** [benoitc/gunicorn#2402]
Hello,

I've been using Gunicorn 20.0.2 for a while, but started getting `AttributeError: 'Response' object has no attribute 'status_code'`like down below;

```Error handling request /socket.io/?EIO=4&transport=websocket
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 114, in handle_request
    resp.write(item)
File "/usr/local/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 326, in write
  self.send_headers()
File "/usr/local/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 318, in send_headers
  tosend = self.default_headers()
File "/usr/local/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 299, in default_headers
  elif self.should_close():
File "/usr/local/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 219, in should_close
  if self.status_code < 200 or self.status_code in (204, 304):
AttributeError: 'Response' object has no attribute 'status_code'
```

So to take care of that I was advised that I should update the version, but when I update gunicorn to 20.0.3 or 20.0.4 I start getting dozens of Critical Worker Timeouts. My stack mostly consists of Flask-SocketIO so I use a single worker configuration. I have no problem or whatsoever with 20.0.2, any idea how can I fix it?

**Comment by moelliDo** [comment]
I've got the same issue with the uvicorn-gunicorn-fastapi Docker-Image (using the python-3.7 one) which already uses gunicorn 20.0.4.

**Comment by tilgovi** [comment]
@umityayla please see if the newer versions of Gunicorn solve your issue, and if not please let us know if there's anything more we can do to investigate.
